# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Just the Class
description: A Jekyll theme for course websites.
author: Kevin Lin
email: me@example.com
baseurl: '/just-the-class' # the subpath of your site, e.g. /blog
url: 'https://kevinl.info' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.2.7
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
nav_links:
  Okpy:
    - 'https://okpy.org'
  Gradescope:
    - 'https://gradescope.com'
  Piazza:
    - 'https://piazza.com'
aux_links:
  'Kevin Lin':
    - 'https://kevinl.info'
  'Just the Class on GitHub':
    - 'https://github.com/kevinlin1/just-the-class'
footer_content: "Based on <a href=\"https://github.com/pmarsceill/just-the-docs\">Just the Docs</a> by Patrick Marsceill."
nav_footer_content: "Powered by <a href=\"https://github.com/kevinlin1/just-the-class\">Just the Class</a>"

# Collections for website data
collections:
  - modules
  - announcements
  - staffers
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
